config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    resources :orders do
      collection do
        post :search
        get :to_pdf
        post :create_tag
      end
      member do
        get :download_pdf
      end
    end

    resources :items

    resources :tags do
      collection do
        post :search
      end
      member do
        get :download_pdf
      end
    end

  end

end

app/models/order.rb
class Order < ApplicationRecord

  # acts_as_paranoid

  include PdfUtils::OrderPdfUtil

  has_many :items
  has_many :order_tags
  has_many :tags, through: :order_tags

  validates :name, presence: true
  validates :tel, presence: true
  validates :code, presence: true

  # has_paper_trail

  def self.getConn params
    conn = [[]]

    if params[:name].to_s.strip.present?
      conn[0] << 'orders.name like ?'
      conn << "%#{params[:name].to_s.strip}%"
    end

    if params[:code].to_s.strip.present?
      conn[0] << 'orders.code like ?'
      conn << "%#{params[:code].to_s.strip}%"
    end

    if params[:total_amout_from].to_s.strip.present?
      conn[0] << 'orders.total_amout >= ?'
      conn << "#{params[:total_amout_from].to_s.strip}"
    end

    if params[:total_amout_to].to_s.strip.present?
      conn[0] << 'orders.total_amout <= ?'
      conn << "#{params[:total_amout_to].to_s.strip}"
    end

    conn[0] = conn[0].join(' and ')
    conn.flatten!
    conn
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminBaseController

  before_action :find_order, only: [:edit, :update]

  def index
    # PaperTrail::Version.all
    @orders = Order.includes(:items).references(:items).all.page(params[:page]).per(50).order("orders.id desc")
  end

  def search
    con = Order.getConn params
    @orders = Order.includes(:items).references(:items).where(con).all.page(params[:page]).per(50).order("orders.id desc")
    render :index
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new order_params
    @order.code = Time.now.strftime('%y%m%d-%H')
    @order.amout = @order.amout.to_f + @order.handling_amout.to_f
    @order.total_amout = @order.amout.to_i
    @order.capital_total_amout = number_to_capital_zh @order.total_amout
    if @order.valid?
      @order.save
      flash[:notice] = '新建成功！'
      redirect_to edit_admin_order_path @order
    else
      render :new
    end
  end

  def edit

  end

  def update
    old_handling_amout = @order.handling_amout
    @order.attributes = order_params
    @order.amout = @order.amout.to_f + @order.handling_amout.to_f - old_handling_amout.to_i
    @order.total_amout = @order.amout.to_i
    @order.capital_total_amout = number_to_capital_zh @order.total_amout
    if @order.valid?
      @order.save
      flash[:notice] = '更新成功！'
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @order = Order.find_by_id(params[:id])
    Order.transaction do
      begin
        @order.destroy
        @order.tags.destroy_all
        @order.order_tags.destroy_all
        flash[:notice] = '删除成功'
      rescue Exception => e
        puts e.message
        flash[:notice] = '删除失败'
        raise ActiveRecord::Rollback
      end
    end
    redirect_to action: :index
  end

  # 下载pdf
  def download_pdf
    html = ''
    file_name = UUIDTools::UUID.random_create
    order = Order.find_by_id(params[:id])
    # html = get_context(params, article) if article.present?
    html = get_context order
    if html.blank?
      flash[:notice] = "数据不存在。"
      return redirect_to admin_orders_path
    end
    pdf = PdfUtil.config(html, 'page')
    pdf.to_file("order", "#{file_name}.pdf")
    path = "#{Rails.root.to_s}/tmp/pdf/order/#{file_name}.pdf" rescue nil
    if path.blank?
      flash[:notice] = t('no_data')
      return redirect_to admin_orders_path unless path
    end
    send_file(path, filename: encode_file_name("出货清单.pdf"))
  end

  def create_tag
    save_status = '1'
    ids = params[:ids].split(',')
    orders = Order.find(ids)
    Order.transaction do
      begin
        tag = Tag.new
        tag.save
        orders.each_with_index do |order, index|
          order_tag = OrderTag.new
          order_tag.tag_id = tag.id
          order_tag.order_id = order.id
          order_tag.save
          tag.name += ',' if index != 0
          tag.name = tag.name.to_s + order.name + '-' + order.code
          tag.number = tag.number.to_i + order.number.to_i
          order.make_time = order.make_time.to_i + 1
          order.save
        end
        tag.save
        save_status = '2'
      rescue Exception => e
        puts e.message
        save_status = '3'
        raise ActiveRecord::Rollback
      end
    end
    render json: {save_status: save_status}
  end

  # def to_pdf
  #   # 1 生成pdf文件 （指定模板）
  #   make_pdf template: "admin/events/to_pdf2.html.erb", filepath: File.join("#{Rails.root.to_s}/tmp/pdf/", "to_pdf2.pdf")
  #   # 2 生成pdf文件 （不指定模板，默认当前action对应的模板）
  #   make_pdf filepath: File.join("#{Rails.root.to_s}/tmp/pdf/", "to_pdf.pdf")
  #   # 3,直接推送
  #   make_and_send_pdf "send_pdf.pdf", template: "admin/events/to_pdf2.html.erb"
  # end

  # def undo_link
    # view_context.link_to("undo", revert_version_path(@product.versions.scoped.last), :method => :post)
  # end

  private

  def find_order
    @order = Order.find_by_id(params[:id])
    @items = @order.items.order('items.id asc')
    if @order.blank?
      flash[:error] = t('no_data')
      redirect_to action: :index
    end
  end

  def order_params
    params.fetch(:order, {}).permit(:name, :tel, :handling_amout, :handling_description, :maker_name);
  end

  # 获取模板以及将模板中需要动态显示数据的地方，把数据获取到
  def get_context order
    template = get_template
    return order.context!(template)
  end

  # 获取模板
  def get_template
    template = ''
    tmp = File.new("#{Rails.root.to_s}/public/files/glass_list1.html").read
    template += tmp
    template
  end

end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper

  

end

app/views/admin/orders/_form.html.erb
<%= form_for(:order, url: @order.new_record? ? admin_orders_path : admin_order_path(@order), method: @order.new_record? ? :post : :put) do |f| %>
<%= error_messages_for :order%>
<div class="panel-body">
  <div class="row">
    <div class="col-md-6">
      <p>「<span class="symbol required"></span>」は必須項目であることを表します。</p>
    </div>
    <div class="col-md-3">
      <button class="btn btn-orange btn-block" type="button" onclick="location.href='<%= admin_orders_path%>'"> <i class="fa fa-arrow-circle-left"></i>
        取消
      </button>
    </div>
    <div class="col-md-3">
      <button class="btn btn-blue btn-block" type="submit">
        保存
        <i class="fa fa-arrow-circle-right"></i>
      </button>
    </div>
  </div>
  <hr>

  <div class="row">
    <div class="col-md-12">
      <div class="errorHandler alert alert-danger no-display">
        <i class="fa fa-times"></i>
        输入的内容不正确，请确认后输入
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label class="control-label">客户姓名<span class="symbol required"></span></label>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label class="control-label">客户电话<span class="symbol required"></span></label>
        <%= f.text_field :tel, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label class="control-label">加工费用<span class="symbol"></span></label>
        <%= f.text_field :handling_amout, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label class="control-label">加工说明<span class="symbol"></span></label>
        <%= f.text_field :handling_description, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label class="control-label">制单人<span class="symbol"></span></label>
        <%= f.text_field :maker_name, class: 'form-control' %>
      </div>
    </div>
  </div>
</div>
<% end %>

<script type="text/javascript">
    $(function(){

    })
</script>

app/views/admin/orders/index.html.erb
<div class="toolbar row">
  <div class="col-sm-6 hidden-xs">
    <div class="page-header">
      <h3>订单管理 <small>订单一览</small></h3>
    </div>
  </div>
  <div class="col-sm-6 col-xs-12">
    <div class="toolbar-tools pull-right">
      <!-- start: TOP NAVIGATION MENU -->
      <ul class="nav navbar-right">
        <!-- start: TO-DO DROPDOWN -->
        <li class="dropdown">
          <button class="btn btn-orange add-row" onclick="javascript:location.href='<%= new_admin_order_path %>'">
            新建订单 <i class="fa fa-plus"></i>
          </button>
        </li>
      </ul>
      <!-- end: TOP NAVIGATION MENU -->
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li>
        <%= link_to '订单管理', admin_orders_path %>
      </li>
      <li class="active">
        订单一览
      </li>
    </ol>
  </div>
</div>

<%= render 'admin/common/messages'%>
<div class="row">
  <div class="col-md-12">
    <!-- start: FORM VALIDATION 1 PANEL -->
    <div class="panel panel-white">
      <div class="panel-heading">
        <h4><i class="fa fa-search"></i> 检索</h4>
        <div class="panel-tools">
          <div class="dropdown">
            <a class="panel-collapse collapses" href="#"><i class="fa fa-angle-up"></i> <span>Collapse</span> </a>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <p>
          请输入检索条件。
        </p>
        <hr>
        <%= form_tag search_admin_orders_path, class: 'form-search' do %>
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <label class="control-label">
                客户姓名
              </label>
              <%= text_field_tag :name, params[:name],class:'form-control' %>
            </div>
          </div>
          <!--<div class="col-md-4">-->
            <!--<div class="form-group">-->
              <!--<label class="control-label">-->
                <!--利用できる機能-->
              <!--</label>-->
            <!--</div>-->
          <!--</div>-->
          <div class="col-md-4">
            <div class="form-group">
              <label class="control-label">
                任务单编码
              </label>
              <%= text_field_tag :code, params[:code],class:'form-control' %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <label class="control-label">
                总货款
              </label>
              <div>
              <%= text_field_tag :total_amout_from, params[:total_amout_from],style:'width:45%;height:34px;display:inline_block' %> ~
              <%= text_field_tag :total_amout_to, params[:total_amout_to],style:'width:45%;height:34px;display:inline_block' %>
              </div>
            </div>
          </div>
          <!-- <div class="col-md-4">
            <div class="form-group">
              <label class="control-label">
                管理者権限
              </label>
              <%#= select_tag :admin_role_id, options_for_select(AdminRole.all.collect { |p| [ p.name, p.id ] }, params[:admin_role_id]), {include_blank: true, class: 'form-control'}%>
            </div>
          </div> -->
        </div>
        <div class="row">
          <div class="col-md-5">
          </div>
          <div class="col-md-7">
            <button class="btn btn-info" type="submit">
              检索 <i class="fa fa-search"></i>
            </button>
            <button class="btn btn-yellow" type="reset">
              清空条件 <i class="fa fa-rotate-left"></i>
            </button>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <!-- end: FORM VALIDATION 1 PANEL -->
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <!-- start: DYNAMIC TABLE PANEL -->
    <div class="panel panel-white">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-list"></i> 检索结果 <span class="text-bold">订单一览</span></h4>
        <div class="panel-tools">
          <div class="dropdown">
            <a data-toggle="dropdown" class="btn btn-xs dropdown-toggle btn-transparent-grey">
              <i class="fa fa-cog"></i>
            </a>
            <ul class="dropdown-menu dropdown-light pull-right" role="menu">
              <li>
                <a class="panel-collapse collapses" href="#"><i class="fa fa-angle-up"></i> <span>Collapse</span> </a>
              </li>
              <li>
                <a class="panel-refresh" href="#">
                  <i class="fa fa-refresh"></i> <span>Refresh</span>
                </a>
              </li>
              <li>
                <a class="panel-expand" href="#">
                  <i class="fa fa-expand"></i> <span>Fullscreen</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <!--<div class="row">
            <div class="col-md-12 space20">
                <div class="btn-group pull-right">
                    <button data-toggle="dropdown" onclick="javascript:location.href='#'" class="btn btn-green dropdown-toggle">
                        CSVダウンロード
                        <i class="fa fa-cloud-download"></i>
                    </button>
                </div>
            </div>
        </div>-->
        <div id="sample_1_wrapper" class="dataTables_wrapper no-footer">
          <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1" role="grid" aria-describedby="sample_1_info">
            <thead>
            <tr role="row">
                <th></th>
                <th>客户姓名</th>
                <th>任务单编码</th>
                <th>总货款</th>
                <th>总货款(大写)</th>
                <th>总数量(块)</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <% if @orders.present? %>
                <% @orders.each do |order| %>
                    <tr>
                      <td><input type="checkbox" value="<%= order.id %>" class="order_check" /></td>
                      <td class="center"><%= order.name %></td>
                      <td class="center"><%= order.code %></td>
                      <td class="center"><%= order.total_amout %></td>
                      <td class="center"><%= order.capital_total_amout %></td>
                      <td class="center"><%= order.number %></td>
                      <td class="center">
                        <div class="visible-md visible-lg hidden-sm hidden-xs">
                          <!-- <a class="btn btn-xs btn-blue tooltips" title="" href="#" onclick="save_order(this, <%= order.id %>)" data-original-title="保存">
                              <i class="fa fa-check"></i>
                          </a> -->
                          <%= link_to((edit_admin_order_path(order)), class: 'btn btn-xs btn-blue tooltips', title: "编辑") do%>
                              <i class="fa fa-edit"></i>
                          <% end %>
                          <%= link_to(admin_order_path(order), data: { confirm: '确定要删除此条数据吗？' }, method: :delete, class: 'btn btn-xs btn-red tooltips', title: '删除') do%>
                              <i class="fa fa-times fa fa-white"></i>
                          <% end %>
                          <%= link_to(download_pdf_admin_order_path(order), class: 'btn btn-xs btn-red tooltips', title: '生成pdf') do%>
                              <i class="fa fa-download"></i>
                          <% end %>
                        </div>

                      </td>
                    </tr>
                <% end %>
            <% else %>
                <tr>
                  <td class="center" colspan="7"><%=I18n.t("messages.no_data")%></td>
                </tr>
            <% end %>
            </tbody>
          </table>
          <div style="text-align:center">
            <button class="btn btn-info" type="button" onclick="save_tag();">
              生成标签书 <i class="fa fa-plus"></i>
            </button>
          </div>
          <div class="dataTables_info" role="status" aria-live="polite">
            <%= page_entries_info @orders %>
          </div>
          <div class="dataTables_paginate paging_simple_numbers">
            <%= paginate @orders, :params => params, window: 3 %>
          </div>
        </div>
      </div>
    </div>
    <!-- end: DYNAMIC TABLE PANEL -->
  </div>
</div>

<script>
  function save_tag(){
    ids = '';
    $('.order_check').each(function(){
      if(this.checked){
        ids = ids + $(this).val() + ',';
      }
    });
    $('#locked').show();
    $.ajax({
      url: '<%= create_tag_admin_orders_path %>',
      type: 'post',
      data: {
        ids: ids,
      },
      dataType: 'json',
      success: function(data){
        $('#locked').hide();
        if(data['save_status'] == '1'){
          alert('输入的数据有误，请确认！');
        }else if(data['save_status'] == '3'){
          alert('发生异常，请刷新后重试！');
        }else if(data['save_status'] == '2'){
          alert('制作标签书成功，请前往标签书一览进行打印');
        }
      },
    });
  }
</script>

app/views/admin/orders/new.html.erb
<div class="toolbar row">
  <div class="col-sm-6 hidden-xs">
    <div class="page-header">
      <h3>订单管理<small>新建订单</small></h3>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li>
        <%= link_to '订单管理', admin_orders_path %>
      </li>
      <li class="active">
        新建订单
      </li>
    </ol>
  </div>
</div>

<%= render 'admin/common/messages'%>

<div class="row">
  <div class="col-md-12">
    <!-- start: FORM VALIDATION 2 PANEL -->
    <div class="panel panel-white">
      <div class="panel-heading">
        <h4 class="panel-title"> <i class="fa fa-globe"></i>
          订单
          <span class="text-bold">新建</span>
        </h4>
      </div>

      <%= render 'form', order: @order %>
    </div>
  </div>
</div>