config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    resources :orders do
      collection do
        post :search
        get :to_pdf
        post :create_tag
      end
      member do
        get :download_pdf
      end
    end

    resources :items

    resources :tags do
      collection do
        post :search
      end
      member do
        get :download_pdf
      end
    end

  end

end

app/models/tag.rb
class Tag < ApplicationRecord

  # acts_as_paranoid

  include PdfUtils::TagPdfUtil

  has_many :order_tags
  has_many :orders, through: :order_tags

  def self.getConn params
    conn = [[]]

    if params[:name].to_s.strip.present?
      conn[0] << 'tags.name like ?'
      conn << "%#{params[:name].to_s.strip}%"
    end

    if params[:number_from].to_s.strip.present?
      conn[0] << 'tags.number >= ?'
      conn << "#{params[:number_from].to_s.strip}"
    end

    if params[:number_to].to_s.strip.present?
      conn[0] << 'tags.number <= ?'
      conn << "#{params[:number_to].to_s.strip}"
    end

    conn[0] = conn[0].join(' and ')
    conn.flatten!
    conn
  end

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::AdminBaseController

  def index
    @tags = Tag.all.page(params[:page]).per(50).order("tags.id desc")
    @tags.each do |tag|
      tag.number = 0
      tag.order_tags.each do |order_tag|
        order_tag.order.items.each do |item|
          tag.number += item.number
        end
      end
    end
  end

  def search
    con = Tag.getConn params
    @tags = Tag.where(con).all.page(params[:page]).per(50).order("tags.id desc")
    render :index
  end

  def destroy
    @tag = Tag.find_by_id(params[:id]);
    if @tag.destroy
      flash[:notice] = '删除成功'
    else
      flash[:notice] = '删除失败'
    end
    redirect_to action: :index
  end

  # 下载pdf
  def download_pdf
    html = ''
    file_name = UUIDTools::UUID.random_create
    tag = Tag.find_by_id(params[:id])
    # html = get_context(params, article) if article.present?
    html = get_context tag
    if html.blank?
      flash[:notice] = "数据不存在。"
      return redirect_to admin_tags_path
    end
    pdf = PdfUtil.config(html)
    pdf.to_file("order", "#{file_name}.pdf")
    path = "#{Rails.root.to_s}/tmp/pdf/order/#{file_name}.pdf" rescue nil
    if path.blank?
      flash[:notice] = t('no_data')
      return redirect_to admin_tags_path unless path
    end
    send_file(path, filename: encode_file_name("标签书.pdf"))
  end

  private

  # 获取模板以及将模板中需要动态显示数据的地方，把数据获取到
  def get_context tag
    template = get_template
    return tag.context!(template)
  end

  # 获取模板
  def get_template
    template = ''
    tmp = File.new("#{Rails.root.to_s}/public/files/tag_list.html").read
    template += tmp
    template
  end

end

app/views/admin/tags/index.html.erb
<div class="toolbar row">
  <div class="col-sm-6 hidden-xs">
    <div class="page-header">
      <h3>标签书管理 <small>标签书一览</small></h3>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li>
        <%= link_to '标签书管理', admin_tags_path %>
      </li>
      <li class="active">
        标签书一览
      </li>
    </ol>
  </div>
</div>

<%= render 'admin/common/messages'%>
<div class="row">
  <div class="col-md-12">
    <!-- start: FORM VALIDATION 1 PANEL -->
    <div class="panel panel-white">
      <div class="panel-heading">
        <h4><i class="fa fa-search"></i> 检索</h4>
        <div class="panel-tools">
          <div class="dropdown">
            <a class="panel-collapse collapses" href="#"><i class="fa fa-angle-up"></i> <span>Collapse</span> </a>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <p>
          请输入检索条件。
        </p>
        <hr>
        <%= form_tag search_admin_tags_path, class: 'form-search' do%>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label">
                标签书名字
              </label>
              <%= text_field_tag :name, params[:name],class:'form-control'%>
            </div>
          </div>
          <!--<div class="col-md-4">-->
            <!--<div class="form-group">-->
              <!--<label class="control-label">-->
                <!--利用できる機能-->
              <!--</label>-->
            <!--</div>-->
          <!--</div>-->
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label">
                总数量
              </label>
              <div>
              <%= text_field_tag :number_from, params[:number_from],style:'width:45%;height:34px;display:inline_block' %> ~
              <%= text_field_tag :number_to, params[:number_to],style:'width:45%;height:34px;display:inline_block' %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-5">
          </div>
          <div class="col-md-7">
            <button class="btn btn-info" type="submit">
              检索 <i class="fa fa-search"></i>
            </button>
            <button class="btn btn-yellow" type="reset">
              清空条件 <i class="fa fa-rotate-left"></i>
            </button>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <!-- end: FORM VALIDATION 1 PANEL -->
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <!-- start: DYNAMIC TABLE PANEL -->
    <div class="panel panel-white">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-list"></i> 检索结果 <span class="text-bold">标签书一览</span></h4>
        <div class="panel-tools">
          <div class="dropdown">
            <a data-toggle="dropdown" class="btn btn-xs dropdown-toggle btn-transparent-grey">
              <i class="fa fa-cog"></i>
            </a>
            <ul class="dropdown-menu dropdown-light pull-right" role="menu">
              <li>
                <a class="panel-collapse collapses" href="#"><i class="fa fa-angle-up"></i> <span>Collapse</span> </a>
              </li>
              <li>
                <a class="panel-refresh" href="#">
                  <i class="fa fa-refresh"></i> <span>Refresh</span>
                </a>
              </li>
              <li>
                <a class="panel-expand" href="#">
                  <i class="fa fa-expand"></i> <span>Fullscreen</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <div id="sample_1_wrapper" class="dataTables_wrapper no-footer">
          <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer" id="sample_1" role="grid" aria-describedby="sample_1_info">
            <thead>
            <tr role="row">
                <th>标签书名字</th>
                <th>总数量(块)</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <% if @tags.present? %>
                <% @tags.each do |tag| %>
                    <tr>
                      <td class="center"><%= tag.name %></td>
                      <td class="center"><%= tag.number %></td>
                      <td class="center">
                        <div class="visible-md visible-lg hidden-sm hidden-xs">
                          <%= link_to(admin_tag_path(tag), data: { confirm: '确定要删除此条数据吗？' }, method: :delete, class: 'btn btn-xs btn-red tooltips', title: '删除') do%>
                              <i class="fa fa-times fa fa-white"></i>
                          <% end %>
                          <%= link_to(download_pdf_admin_tag_path(tag), class: 'btn btn-xs btn-red tooltips', title: '生成pdf') do%>
                              <i class="fa fa-download"></i>
                          <% end %>
                        </div>

                      </td>
                    </tr>
                <% end %>
            <% else %>
                <tr>
                  <td class="center" colspan="3"><%=I18n.t("messages.no_data")%></td>
                </tr>
            <% end %>
            </tbody>
          </table>
          <div class="dataTables_info" role="status" aria-live="polite">
            <%= page_entries_info @tags %>
          </div>
          <div class="dataTables_paginate paging_simple_numbers">
            <%= paginate @tags, :params => params, window: 3 %>
          </div>
        </div>
      </div>
    </div>
    <!-- end: DYNAMIC TABLE PANEL -->
  </div>
</div>